[phases.setup]
nixPkgs = ["nodejs-20_x", "python3"]

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps --include=dev",
  "npx prisma generate"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
